version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: vulnerable-webapp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vulnerable_webapp}
      POSTGRES_USER: ${POSTGRES_USER:-webapp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-webapp_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - webapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-webapp_user} -d ${POSTGRES_DB:-vulnerable_webapp}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: vulnerable-webapp-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://${POSTGRES_USER:-webapp_user}:${POSTGRES_PASSWORD:-webapp_password}@postgres:5432/${POSTGRES_DB:-vulnerable_webapp}
      JWT_SECRET: ${JWT_SECRET:-weak-secret-key-for-education}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-weak-refresh-secret}
      PORT: ${BACKEND_PORT:-3001}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
      UPLOAD_MAX_SIZE: ${UPLOAD_MAX_SIZE:-10485760}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-900000}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    networks:
      - webapp-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: vulnerable-webapp-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3001}
      VITE_APP_NAME: ${VITE_APP_NAME:-Vulnerable Task Manager}
      VITE_APP_VERSION: ${VITE_APP_VERSION:-1.0.0}
    ports:
      - "${FRONTEND_PORT:-3000}:${BUILD_TARGET:-development == 'production' && '80' || '3000'}"
    depends_on:
      - backend
    networks:
      - webapp-network
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local
  backend_logs:
    driver: local

networks:
  webapp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16