apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: vulnerable-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vulnerable-webapp-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "https://yourdomain.com/api"
        - name: VITE_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: vulnerable-webapp-config
              key: VITE_APP_NAME
        - name: VITE_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: vulnerable-webapp-config
              key: VITE_APP_VERSION
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vulnerable-webapp
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
