apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vulnerable-webapp-ingress
  namespace: vulnerable-webapp
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "vulnerable-webapp-ip"
    networking.gke.io/managed-certificates: "vulnerable-webapp-ssl"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: yourdomain.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: vulnerable-webapp-ssl
  namespace: vulnerable-webapp
spec:
  domains:
    - yourdomain.com
